name: Create Docker Image For PrivateRouter SimpleX

# This allows us to call this build from a url request if the type(s) matches
on:
  repository_dispatch:
    types: build-image

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      # Clone our repo
      - name: Clone project
        uses: actions/checkout@v3 

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN_NAME }}
          password: ${{ secrets.DOCKER_LOGIN_PASS }}

      # Set up QEMU for Multi-Arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Set up Docker BuildX for Multi-Arch builds
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      # Pull in our newest build tag from our Release Repo
      - name: Set environment variable
        run: |
          GIT_DATA=$(curl --silent https://api.github.com/repos/PrivateRouter-LLC/simplex-releases/tags\?per_page\=1)
          echo "LATEST_TAG=$(echo ${GIT_DATA} | jq -r '.[].name')" >> $GITHUB_ENV

      # Issue the build command for the image and push it to the Docker Hub Registry, BuildX is used automatically
      - name: Build SimpleX Container
        run: |
          docker build -t privaterouterllc/simplex:${{ env.LATEST_TAG }} -t privaterouterllc/simplex:latest --push --platform 'linux/amd64,linux/arm64,linux/arm/v7' .

